P8105_hw2_yz4719
================
Yuxin Zhang
2023-10-03

``` r
library(tidyverse)
library(readxl)
```

## Problem 1: FiveThirtyEight data

``` r
# replace month number with month name
month_df = 
  tibble(
    month_num = 1:12,
    month_abb = month.abb,
    month = month.name
  )

# clean the data in pols-month.csv
pols = 
  read_csv("data/fivethirtyeight_datasets/pols-month.csv") |>
  # Use separate() to break up the variable mon into integer variables year, month, and day
  separate(mon, into = c("year", "month_num", "day"), convert = TRUE) |>
  # create a president variable taking values gop and dem
  mutate(
    president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop")) |>
  #  remove prez_dem and prez_gop; and remove the day variable
  left_join(x = _, y = month_df) |> 
  select(year, month, everything(), -day, -starts_with("prez")) 
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## Joining with `by = join_by(month_num)`

``` r
snp = 
  read_csv(
    "data/fivethirtyeight_datasets/snp.csv",
    col_types = cols(date = col_date(format = "%m/%d/%y"))) |>
  separate(date, into = c("year", "month_num", "day"), convert = TRUE) |>
  mutate(
    year = if_else(year > 2023, year - 100, year)) |> 
  left_join(x = _, y = month_df) |> 
  select(year, month, close) 
```

    ## Joining with `by = join_by(month_num)`

``` r
unemployment = 
  read_csv("data/fivethirtyeight_datasets/unemployment.csv") |>
  rename(year = Year) |>
  pivot_longer(
    Jan:Dec, 
    names_to = "month_abb",
    values_to = "unemployment"
  ) |> 
  left_join(x = _, y = month_df) |> 
  select(year, month, unemployment)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## Joining with `by = join_by(month_abb)`

``` r
data_538 = 
  left_join(pols, snp) |>
  left_join(x = _, y = unemployment)
```

    ## Joining with `by = join_by(year, month)`
    ## Joining with `by = join_by(year, month)`

``` r
str(data_538)
```

    ## tibble [822 × 13] (S3: tbl_df/tbl/data.frame)
    ##  $ year        : num [1:822] 1947 1947 1947 1947 1947 ...
    ##  $ month       : chr [1:822] "January" "February" "March" "April" ...
    ##  $ month_num   : int [1:822] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ gov_gop     : num [1:822] 23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_gop     : num [1:822] 51 51 51 51 51 51 51 51 51 51 ...
    ##  $ rep_gop     : num [1:822] 253 253 253 253 253 253 253 253 253 253 ...
    ##  $ gov_dem     : num [1:822] 23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_dem     : num [1:822] 45 45 45 45 45 45 45 45 45 45 ...
    ##  $ rep_dem     : num [1:822] 198 198 198 198 198 198 198 198 198 198 ...
    ##  $ president   : chr [1:822] "dem" "dem" "dem" "dem" ...
    ##  $ month_abb   : chr [1:822] "Jan" "Feb" "Mar" "Apr" ...
    ##  $ close       : num [1:822] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ unemployment: num [1:822] NA NA NA NA NA NA NA NA NA NA ...

### Description of datasets

The `pols` data has 822 observations and 11 variables and tells us about
the party affiliation distribution (democrat or republican) for
governors and senators for a given year from years 1947 to 2015. It also
tells us whether the sitting president was a democrat or republican. The
`snp` data has 787 observations and 3 variables, ranging from years 1950
to 2015. The `unemployment` data has 816 observations and 3 variables
ranging from years 1948 to 2015. In Januarys in or after 1975 in which a
democrat was president, the **average unemployment rate was 6.57**. The
average unemployment rate over the same time period in which a
republican was president was 6.47.

## Problem 2

``` r
mr_trash_wheel_df = 
   read_excel("data/Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N586")|>
  janitor::clean_names()|>
  mutate(
    date = substr(date, nchar(date) - 1, nchar(date)))|>
  mutate(
    homes_powered = (weight_tons*500/30))|>
  mutate(trash_wheel_name = "Mr_trash_wheel")
mr_trash_wheel_df
```

    ## # A tibble: 584 × 15
    ##    dumpster month year  date  weight_tons volume_cubic_yards plastic_bottles
    ##       <dbl> <chr> <chr> <chr>       <dbl>              <dbl>           <dbl>
    ##  1        1 May   2014  16           4.31                 18            1450
    ##  2        2 May   2014  16           2.74                 13            1120
    ##  3        3 May   2014  16           3.45                 15            2450
    ##  4        4 May   2014  17           3.1                  15            2380
    ##  5        5 May   2014  17           4.06                 18             980
    ##  6        6 May   2014  20           2.71                 13            1430
    ##  7        7 May   2014  21           1.91                  8             910
    ##  8        8 May   2014  28           3.7                  16            3580
    ##  9        9 June  2014  05           2.52                 14            2400
    ## 10       10 June  2014  11           3.76                 18            1340
    ## # ℹ 574 more rows
    ## # ℹ 8 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   sports_balls <dbl>, homes_powered <dbl>, trash_wheel_name <chr>

``` r
professor_trash_wheel_df = 
  read_excel("data/Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", range = "A2:M108")|>
  janitor::clean_names()|>
  mutate(
    date = substr(date, nchar(date) - 1, nchar(date)))|>
  mutate(
    homes_powered = (weight_tons*500/30), 
    year = as.character(year))|>
  mutate(trash_wheel_name = "Professor_trash_wheel")
professor_trash_wheel_df
```

    ## # A tibble: 106 × 14
    ##    dumpster month    year  date  weight_tons volume_cubic_yards plastic_bottles
    ##       <dbl> <chr>    <chr> <chr>       <dbl>              <dbl>           <dbl>
    ##  1        1 January  2017  02           1.79                 15            1950
    ##  2        2 January  2017  30           1.58                 15            9540
    ##  3        3 February 2017  26           2.32                 18            8350
    ##  4        4 February 2017  26           3.72                 15            8590
    ##  5        5 February 2017  28           1.45                 15            7830
    ##  6        6 March    2017  30           1.71                 15            8210
    ##  7        7 April    2017  01           1.82                 15            9830
    ##  8        8 April    2017  20           2.37                 15            9240
    ##  9        9 May      2017  10           2.64                 15            9540
    ## 10       10 May      2017  26           2.78                 15            8230
    ## # ℹ 96 more rows
    ## # ℹ 7 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>, trash_wheel_name <chr>

``` r
gwynnda_trash_wheel_df = 
  read_excel("data/Trash Wheel Collection Data.xlsx", sheet = "Gwynnda Trash Wheel", range = "A2:L157")|>
  janitor::clean_names()|>
  mutate(
    date = substr(date, nchar(date) - 1, nchar(date))
  )|>
  mutate(
    homes_powered = (weight_tons*500/30),
    year = as.character(year)
  )|>
  mutate(trash_wheel_name = "Gwynnda_trash_wheel")
gwynnda_trash_wheel_df
```

    ## # A tibble: 155 × 13
    ##    dumpster month  year  date  weight_tons volume_cubic_yards plastic_bottles
    ##       <dbl> <chr>  <chr> <chr>       <dbl>              <dbl>           <dbl>
    ##  1        1 July   2021  03           0.93                 15            1200
    ##  2        2 July   2021  07           2.26                 15            2000
    ##  3        3 July   2021  07           1.62                 15            1800
    ##  4        4 July   2021  16           1.76                 15            1000
    ##  5        5 July   2021  30           1.53                 15            2100
    ##  6        6 August 2021  11           2.06                 15            2400
    ##  7        7 August 2021  14           1.9                  15            2700
    ##  8        8 August 2021  16           2.16                 15            3000
    ##  9        9 August 2021  16           2.6                  15             980
    ## 10       10 August 2021  17           3.21                 15             240
    ## # ℹ 145 more rows
    ## # ℹ 6 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   plastic_bags <dbl>, wrappers <dbl>, homes_powered <dbl>,
    ## #   trash_wheel_name <chr>

``` r
trash_wheel_combind_df=
  bind_rows(mr_trash_wheel_df,professor_trash_wheel_df,gwynnda_trash_wheel_df) |>
  janitor::clean_names()

trash_wheel_combind_df
```

    ## # A tibble: 845 × 15
    ##    dumpster month year  date  weight_tons volume_cubic_yards plastic_bottles
    ##       <dbl> <chr> <chr> <chr>       <dbl>              <dbl>           <dbl>
    ##  1        1 May   2014  16           4.31                 18            1450
    ##  2        2 May   2014  16           2.74                 13            1120
    ##  3        3 May   2014  16           3.45                 15            2450
    ##  4        4 May   2014  17           3.1                  15            2380
    ##  5        5 May   2014  17           4.06                 18             980
    ##  6        6 May   2014  20           2.71                 13            1430
    ##  7        7 May   2014  21           1.91                  8             910
    ##  8        8 May   2014  28           3.7                  16            3580
    ##  9        9 June  2014  05           2.52                 14            2400
    ## 10       10 June  2014  11           3.76                 18            1340
    ## # ℹ 835 more rows
    ## # ℹ 8 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   sports_balls <dbl>, homes_powered <dbl>, trash_wheel_name <chr>

### Description of datasets

Dataset `mr_trash_wheel_df` contains 584 observations and 15 variables
including dumpster, month, year, date, weight_tons, volume_cubic_yards,
plastic_bottles, polystyrene, cigarette_butts, glass_bottles,
plastic_bags, wrappers, sports_balls, homes_powered, trash_wheel_name.

Dataset `professor_trash_wheel_df` contains 106 observations and 14
variables including dumpster, month, year, date, weight_tons,
volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
glass_bottles, plastic_bags, wrappers, homes_powered, trash_wheel_name.

Dataset `gwynnda_trash_wheel_df` contains 155 observations and 13
variables including dumpster, month, year, date, weight_tons,
volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
plastic_bags, wrappers, homes_powered, trash_wheel_name.

**key variables ** In the combind of all three trash wheels, all the
data came from a range of date inbetween year 2014, 2023, and have a
average “weight_tons” of 3.0094793 and standard deviation 0.8135678.
they also have a average “volume_cubic_yards” of 15.1349112 and standard
deviation 1.3457939.

The total weight of trash collected by Professor Trash Wheel is 216.26
tons.

The total number of cigarette butts collected by Gwynnda in July of 2021
is 1.63^{4}.

## Problem 3

``` r
mci_baseline_unfilter = 
  read_csv("data/data_mci/MCI_baseline.csv", skip=1) |> 
  janitor::clean_names() |>
  mutate(
    sex =
      case_match(
        sex,
        1 ~ "male",
        0 ~ "female"),
    sex = as.factor(sex),
    apoe4 = 
      case_match(
        apoe4,
        1 ~ "carrier",
        0 ~ "noncarrier"),
    apoe4 = as.factor(apoe4)
      )
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
mci_baseline = 
  read_csv("data/data_mci/MCI_baseline.csv", skip=1) |> 
  janitor::clean_names() |>
  mutate(
    sex =
      case_match(
        sex,
        1 ~ "male",
        0 ~ "female"),
    sex = as.factor(sex),
    apoe4 = 
      case_match(
        apoe4,
        1 ~ "carrier",
        0 ~ "noncarrier"),
    apoe4 = as.factor(apoe4)
      )|>
  filter((current_age < age_at_onset | age_at_onset == ".")) 
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
view(mci_baseline)
```

### Description of the data

Importing and cleaned the data, then converted sex and apoe4 these 2
variables into meaningful characters.Then remove any participants who do
not meet the stated inclusion criteria.

This study recruited 483 participants， and have 6 variables focus on
age, sex, years of education, APOE4 gene carrier or not, and age at the
onset.

There are 93 participants developed MCI.

The average baseline age was 65.03.

The proportion of women in the study who are apoe4 carriers is 30%.

``` r
mci_amyloid = 
  read_csv("data/data_mci/mci_amyloid.csv", skip=1) |> 
  janitor::clean_names() |> 
rename("id" = "study_id" )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
mci_amyloid_pivot= mci_amyloid|>
  pivot_longer(
    baseline:time_8, 
    names_to = "time",
    values_to = "value"
   ) |>
    arrange(time,id) 
  
view(mci_amyloid)
```

After read the dataset, then use pivot_longer to switch to the long
format. The variable `study_id` was renamed to match the mci_baseline
dataset.

Dataset “mci_amyloid” has 6 variables: id, baseline, time_2, time_4,
time_6, time_8

``` r
mci_combined =
  inner_join(mci_baseline, mci_amyloid, by = "id")

only_baseline =
  anti_join(mci_baseline, mci_combined, by = "id")

only_amyloid =
  anti_join(mci_amyloid, mci_combined, by = "id")

mci_combined_pivot =
  inner_join(mci_baseline, mci_amyloid_pivot, by = "id")
```

Here are some participants who only appear in the baseline data but not
in the amyloid data, and their id is: 14, 49, 92, 179, 268, 304, 389,
412. Here are some participants who only appear in the amyloid data but
not in the baseline data, and their id is 72, 234, 283, 380, 484, 485,
486, 487, 488, 489, 490, 491, 492, 493, 494, 495.

``` r
mci_combined =
  inner_join(mci_baseline, mci_amyloid, by = "id")

view(mci_combined)

write_csv(mci_combined, "mci_combined.csv")
```

Using the inner join function to join the baseline and amyloid datasets
together, so that only participants who appear in both datasets are
retained.

The combined dataset has 471 rows and 8 columns, so there are
